name: backend

on:
  push:
    branches: ["main"]
    paths: ["backend/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        run: cd frontend && docker build \ --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \--build-arg BCRYPT_SALT=${{ secrets.BCRYPT_SALT }} \-build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \ -t listonfermi/task-binaryveda-user-auth .

      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push listonfermi/wenet-user-service
