name: backend

on:
  push:
    branches: ["main"]
    paths: ["backend/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Build the Docker image
      - run: |
          cd backend && docker build \
          --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
          --build-arg BCRYPT_SALT=${{ secrets.BCRYPT_SALT }} \
          --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
          -t listonfermi/task-binaryveda-user-auth .

      # Step 3: Log in to Docker Hub
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Push the Docker image
      - run: docker push listonfermi/task-binaryveda-user-auth
